### PR TITLE
Fix subcommand choices 

### PR DESCRIPTION
**Pull request by zpriddy**

### CODE REVIEW

**Comment by AhmedSoliman** [comment]
Can you please update the PR to include a full description of the problem this is trying to fix? and what was the test plan to verify the fix?

**Comment by zpriddy** [comment]
Sorry about the delay. 

When a subcommand has choices, they are not combined with the choices for the parent command. This change merges both the parent and child command choices. 

There are currently no tests that cover this for interactive shells, so all testing is done manually.

**Comment by ylectric** [comment]
Hey @zpriddy, thanks for working on this!
It's a little bit unclear to me what are the choices you're trying to merge here. The choices are intrinsic to arguments, aren't they? So why one may need to merge them? Maybe you could provide a screenshot to explain?

**Comment by zpriddy** [comment]
If you have a subcommand under a supper command class, the choices for those arguments where not getting listed.. only the choices for the supercommand. 

This is the current version: 
Screen Shot 2019-06-30 at 1 10 52 PM
Screen Shot 2019-06-30 at 1 11 02 PM
Screen Shot 2019-06-30 at 1 11 14 PM

This is the updated version
Screen Shot 2019-06-30 at 1 11 50 PM

```
from termcolor import cprint
from nubia import command, argument, context


@command
@argument("parent_option", name="parent_option", description="Parent Option", choices=["Parent_1", "Parent_2"], positional=False)
class TestCommand:
    """Test command for choices"""


    def __init__(self, parent_option=""):
        self._parent_option = parent_option

    @property
    def parent_option(self):
        return self._parent_option


    @command
    @argument("option", description="Test Choices", positional=False, choices=["Option_1", "Option_2"])
    def my_options(self, option):
        """Test choices"""
        cprint(option)
```

**Comment by AhmedSoliman** [comment]
@zpriddy Great catch! Can you please sign the CLA so we can review and import your fix?

**Comment by zpriddy** [comment]
Done!

**Pull request closed without merging**
