### PR TITLE
Improve: Version bump to 3.7

### PR DESCRIPTION
**Pull request by asamolion**
@ylectric Here is the first step.

I also wanted to know is there a way to run all of the code in the context of Python 3.7 to verify if anything is breaking?

### CODE REVIEW

**Comment by asamolion** [comment]
@ylectric I've created a python3.7 virtualenv using Pipenv and ran the unit tests.

After importing `Union` instead of  `_Union` and running the tests, 22 out of 63 tests fail.

**Comment by asamolion** [comment]
How should I begin fixing this?

**Comment by AhmedSoliman** [comment]
@asamolion I was under the impression that @ylectric is already working on a fix. If this is not accurate, you can take a hit at it and let's see.

**Comment by asamolion** [comment]
Okay @AhmedSoliman, I'll wait for @ylectric's response.

**Comment by ylectric** [comment]
Yes, I'm working on a fix for 3.7 compatibility issues.

@asamolion, regarding for the PR itself, I'm afraid we can't accept this version bump. Sorry for not making myself clear in #2. As Python 3.7 was released just a few months ago, we can't expect it to be already available for all the popular operating systems. We definitely need to be 3.7 compatible, but there's no reason to change the requirement. Please see #2 once again for more details.

This, however, brings a more interesting question to the table. `Pipfile` doesn't allow you to specify a _minimal_ requirement as per https://github.com/pypa/pipenv/issues/1050 thus making `pipenv` issue warnings about the interpreter version and also making `pipenv check` fail. Since @kennethreitz is strongly against supporting this functionality, maybe we shall consider removing the interpreter version requirement from the `Pipfile` and checking it in the runtime. @AhmedSoliman, what do you think?

**Comment by calebmarchent** [comment]
This proposed change _requires_ 3.7, we will retain support for 3.6 for time-being; closing pull-request.

**Pull request closed without merging**
